From ubuntu:latest

USER  manish 
WORKDIR /home/


## copying setup scripts and env file 
COPY ./env/set_env.sh /usr/local/ec2/
RUN sudo rm -rf /etc/profile.d/env.sh
COPY env_script.sh /etc/profile.d/
COPY startup.sh /home/
COPY ./env/env  /home/

## pull latest code of master branch and setup nginx 
RUN sudo mkdir -p /home/docker_project
COPY ./app /home/docker_project

RUN sudo rm -rf /home/docker_project/log && sudo mkdir -p /home/shared/  && \
    sudo ln -sf /home/docker_project/shared/config/dmc.yml /home/app/config/config.yml && \
    sudo ln -sf /home/docker_project/shared/log /home/app/log && \
    sudo rm -rf /home/docker_project/tmp &&  ln -sf /home/ubunt/shared/tmp  /home/app/tmp && \
    sudo sed -i 's/app\/current/app/g' /home/app/config/nginx/qa/nginx.conf && \
    sudo ln -sf /home/docker_project/config/nginx/qa/platform.conf /etc/nginx/platform.conf  && \
    sudo ln -sf /home/docker_project/config/nginx/qa/nginx.conf  /etc/nginx/nginx.conf && \
    sudo chown -R manish:manish /home/  && \
    cd /home/docker_project/  && sudo  gem install bundler -v 1.17.3 --force  && \
    cd /home/docker_project/  &&  bundle install  --without development test --quiet 

ENTRYPOINT bash /home/startup.sh 
EXPOSE 80 443
